### 4.1 使用断言语句进行断言

在测试用例中，pytest允许你使用标准的python断言语句去检测异常和数据。

举个例子：  
```python
# content of test_assert1.py
def f():
    return 3

def test_function():
    assert f() == 4
```
去断言你的函数返回一个确定的值。当断言失败的时候，将返回函数调用信息：
```
$ pytest test_assert1.py
=========================== test session starts ============================
platform linux -- Python 3.x.y, pytest-3.x.y, py-1.x.y, pluggy-0.x.y
rootdir: $REGENDOC_TMPDIR, inifile:
collected 1 item

test_assert1.py F                                                    [100%]

================================= FAILURES =================================
______________________________ test_function _______________________________

    def test_function():
>       assert f() == 4
E       assert 3 == 4
E        +  where 3 = f()

test_assert1.py:5: AssertionError
========================= 1 failed in 0.12 seconds =========================
```
